#!/usr/bin/env bash
# =============================================================================
# borrow_creds.sh — discover REAL API keys from your environment / the CLIs and
# write them to .env.cliauth (gitignored) for the cli-auth e2e profile.
#
# POLICY (honest + safe by default):
#   * CLEAN path  — a real API key (env var, or an api_key in the CLI config).
#     Reused as-is. It's just a key. This is what we wire.
#   * OAUTH path  — a *subscription* token (Claude Pro/Max in the macOS Keychain;
#     ChatGPT tokens in ~/.codex/auth.json). We DETECT it and WARN, but DO NOT
#     wire it. Reasons: (a) using a personal subscription token to back a proxy
#     is against Anthropic/OpenAI consumer ToS and can flag the account;
#     (b) those tokens are validated to come from the real client, so a generic
#     proxy request generally 401s without heavy spoofing that defeats the point.
#     Provision an API key instead — the org has an Anthropic Enterprise license.
#
# This script NEVER prints secret values. It writes them to .env.cliauth only.
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"

ENVFILE=".env.cliauth"
ANTHROPIC_KEY=""
OPENAI_KEY=""
WARN=()

echo "--- discovering credentials (values never printed) ---"

# --- Anthropic ---------------------------------------------------------------
if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
  ANTHROPIC_KEY="$ANTHROPIC_API_KEY"
  echo "Anthropic: using ANTHROPIC_API_KEY from environment (clean)."
elif security find-generic-password -s "Claude Code-credentials" >/dev/null 2>&1; then
  WARN+=("Anthropic: found a Claude Code SUBSCRIPTION token in the macOS Keychain \
(OAuth). NOT wired — ToS-gray and won't work through a generic proxy. Set a real \
ANTHROPIC_API_KEY (Enterprise/workspace key) and re-run.")
elif [[ -f "$HOME/.claude/.credentials.json" ]]; then
  WARN+=("Anthropic: found ~/.claude/.credentials.json (likely OAuth). NOT wired \
— see note above. Provision an ANTHROPIC_API_KEY instead.")
else
  WARN+=("Anthropic: no credential found. Set ANTHROPIC_API_KEY to test the \
Claude Code path.")
fi

# --- OpenAI (Codex) ----------------------------------------------------------
if [[ -n "${OPENAI_API_KEY:-}" ]]; then
  OPENAI_KEY="$OPENAI_API_KEY"
  echo "OpenAI: using OPENAI_API_KEY from environment (clean)."
elif [[ -f "$HOME/.codex/auth.json" ]]; then
  # Extract an api key ONLY if present; ignore OAuth tokens.
  FOUND=$(python3 -c "
import json,sys
try:
    d=json.load(open('$HOME/.codex/auth.json'))
except Exception:
    sys.exit(0)
k=d.get('OPENAI_API_KEY') or ''
print(k if k else '')
" 2>/dev/null || true)
  if [[ -n "$FOUND" ]]; then
    OPENAI_KEY="$FOUND"
    echo "OpenAI: using OPENAI_API_KEY from ~/.codex/auth.json (clean)."
  else
    WARN+=("OpenAI: ~/.codex/auth.json holds ChatGPT SUBSCRIPTION tokens only \
(OAuth). NOT wired — ToS-gray. Set a real OPENAI_API_KEY and re-run.")
  fi
else
  WARN+=("OpenAI: no credential found. Set OPENAI_API_KEY to test the Codex path.")
fi

# --- write .env.cliauth ------------------------------------------------------
MASTER="sk-cliauth-$(python3 -c "import secrets;print(secrets.token_urlsafe(24))")"
{
  echo "# Generated by borrow_creds.sh — gitignored. Do NOT commit."
  echo "LITELLM_MASTER_KEY=$MASTER"
  echo "GATEWAY_URL=http://localhost:4000"
  [[ -n "$ANTHROPIC_KEY" ]] && echo "ANTHROPIC_API_KEY=$ANTHROPIC_KEY"
  [[ -n "$OPENAI_KEY" ]]    && echo "OPENAI_API_KEY=$OPENAI_KEY"
} > "$ENVFILE"
chmod 600 "$ENVFILE"

echo "--- wrote $ENVFILE (master key generated; keys written iff clean) ---"
[[ -n "$ANTHROPIC_KEY" ]] && echo "  Anthropic key: WIRED"   || echo "  Anthropic key: MISSING (Claude Code path won't work)"
[[ -n "$OPENAI_KEY" ]]    && echo "  OpenAI key:    WIRED"   || echo "  OpenAI key:    MISSING (Codex path won't work)"

if (( ${#WARN[@]} )); then
  echo
  echo "!!! NOTES / WARNINGS !!!"
  for w in "${WARN[@]}"; do echo "  - $w"; done
fi
